acme_simple_cms:
    resource: "@AcmeSimpleCMSBundle/Controller/DashboardController.php"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
#posts:
#    type:     rest
#    resource: "@AcmeSimpleCMSBundle/Controller/PostController.php"
#    prefix:   /
#
#users:
#    type:     rest
#    resource: "@AcmeSimpleCMSBundle/Controller/UserController.php"
#    prefix:   /
#
#categories:
#    type:     rest
#    resource: "@AcmeSimpleCMSBundle/Controller/CategoryController.php"
#    prefix:   /
#    
#tags:
#    type:     rest
#    resource: "@AcmeSimpleCMSBundle/Controller/TagController.php"
#    prefix:   /

#dey_sonata_angular_admin:
#    type: 
#    resource:
#    prefix:
        
admin:
    resource: '@DeySonataAngularAdminBundle/Resources/config/routing/sonata_admin.yml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin