acme_simple_cms:
    resource: "@AcmeSimpleCMSBundle/Controller/DashboardController.php"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
posts:
    type:     rest
    resource: "@AcmeSimpleCMSBundle/Controller/PostController.php"
    prefix:   /

users:
    type:     rest
    resource: "@AcmeSimpleCMSBundle/Controller/UserController.php"
    prefix:   /

categories:
    type:     rest
    resource: "@AcmeSimpleCMSBundle/Controller/CategoryController.php"
    prefix:   /
    
tags:
    type:     rest
    resource: "@AcmeSimpleCMSBundle/Controller/TagController.php"
    prefix:   /