acme_simple_cms:
    resource: "@AcmeSimpleCMSBundle/Controller/DashboardController.php"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
posts:
    type:     rest
    resource: "@AcmeSimpleCMSBundle/Controller/PostController.php"
    prefix:   /
    